AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
