AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
